import React, { useState } from "react";
import { X, Save, Sparkles, Code, Globe } from "lucide-react";
import { useEditor } from "../store/EditorContext";
import { toast } from "sonner";
import { motion, AnimatePresence } from "motion/react";
import { Page } from "../types";
import { useTranslation } from "../i18n/TranslationContext";

interface GlobalSettingsModalProps {
  onClose: () => void;
}

const generateSitemapString = (pages: Page[]): string => {
  const baseUrl = "https://yourwebsite.com";
  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`;

  pages.forEach(page => {
    // Basic formatting for sitemap
    const loc = `${baseUrl}${page.path === '/' ? '' : page.path}`;
    xml += `\n  <url>\n    <loc>${loc}</loc>\n    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>${page.path === '/' ? '1.0' : '0.8'}</priority>\n  </url>`;
  });

  xml += `\n</urlset>`;
  return xml;
};

export const GlobalSettingsModal: React.FC<GlobalSettingsModalProps> = ({ onClose }) => {
  const { state, dispatch } = useEditor();
  const { t } = useTranslation();
  const [googleSiteVerif, setGoogleSiteVerif] = useState(
    state.globalSettings?.googleSiteVerification || ""
  );
  const [customHeadCode, setCustomHeadCode] = useState(
    state.globalSettings?.customHeadCode || ""
  );

  const [generatedSitemap, setGeneratedSitemap] = useState<string | null>(null);

  const handleSave = () => {
    dispatch({
      type: "UPDATE_GLOBAL_SETTINGS",
      payload: {
        googleSiteVerification: googleSiteVerif,
        customHeadCode: customHeadCode,
      },
    });
    toast.success("Global settings saved successfully!");
    onClose();
  };

  const handleGenerateSitemap = () => {
    const sitemapStr = generateSitemapString(state.pages);
    setGeneratedSitemap(sitemapStr);
    toast.success("Sitemap generated by Gemini AI!");
  };

  const handleCopySitemap = () => {
    if (generatedSitemap) {
      navigator.clipboard.writeText(generatedSitemap);
      toast.success("Sitemap copied to clipboard");
    }
  };

  return (
    <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 10 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 10 }}
        className="w-full max-w-2xl dark:bg-[#181818] bg-white rounded-xl shadow-2xl border dark:border-[#333] border-gray-200 overflow-hidden flex flex-col max-h-[90vh]"
      >
        <div className="flex items-center justify-between p-4 border-b dark:border-[#333] border-gray-200">
          <h2 className="text-lg font-semibold dark:text-white text-gray-900 flex items-center gap-2">
            <Globe className="w-5 h-5" />
            {t("Global Site Settings")}
          </h2>
          <button
            onClick={onClose}
            className="p-1.5 rounded-md hover:bg-black/5 dark:hover:bg-white/10 dark:text-gray-400 text-gray-500 transition-colors"
          >
            <X size={18} />
          </button>
        </div>

        <div className="p-6 overflow-y-auto flex-1 space-y-6">
          {/* SEO & Meta */}
          <div className="space-y-4">
            <h3 className="text-sm font-semibold dark:text-gray-300 text-gray-700 flex items-center gap-2">
              <Code size={16} />
              {t("SEO & Custom Meta Base")}
            </h3>
            
            <div className="space-y-2">
              <label className="text-xs font-medium dark:text-gray-400 text-gray-500">
                Google Site Console Verification Code
              </label>
              <p className="text-[11px] dark:text-gray-500 text-gray-400 mb-2">
                Paste your Google Search Console verification meta tag here (e.g. &lt;meta name="google-site-verification" content="..." /&gt;)
              </p>
              <input
                type="text"
                placeholder='<meta name="google-site-verification" content="..." />'
                value={googleSiteVerif}
                onChange={(e) => setGoogleSiteVerif(e.target.value)}
                className="w-full dark:bg-[#252525] bg-gray-50 border dark:border-[#444] border-gray-300 rounded-md p-2 text-sm dark:text-gray-200 text-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-colors font-mono"
              />
            </div>

            <div className="space-y-2 pt-2">
              <label className="text-xs font-medium dark:text-gray-400 text-gray-500">
                Custom &lt;head&gt; Code
              </label>
              <p className="text-[11px] dark:text-gray-500 text-gray-400 mb-2">
                Add global analytics scripts, custom fonts, or other meta tags applied to all pages.
              </p>
              <textarea
                rows={4}
                placeholder="<!-- Custom Head Code -->"
                value={customHeadCode}
                onChange={(e) => setCustomHeadCode(e.target.value)}
                className="w-full dark:bg-[#252525] bg-gray-50 border dark:border-[#444] border-gray-300 rounded-md p-2 text-sm dark:text-gray-200 text-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-colors font-mono resize-y"
              />
            </div>
          </div>

          <div className="border-t dark:border-[#333] border-gray-200"></div>

          {/* Sitemap section */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-semibold dark:text-gray-300 text-gray-700">
                {t("Website Sitemap")}
              </h3>
              <button
                onClick={handleGenerateSitemap}
                className="flex items-center space-x-2 px-3 py-1.5 rounded-md text-xs font-medium bg-purple-500/10 text-purple-600 dark:text-purple-400 hover:bg-purple-500/20 border border-purple-500/20 transition-colors"
              >
                <Sparkles size={14} />
                <span>{t("Generate with Gemini AI")}</span>
              </button>
            </div>
            
            <p className="text-[11px] dark:text-gray-500 text-gray-400">
              Generates an XML sitemap based on your current pages and routes, optimized for search engines.
            </p>

            <AnimatePresence>
              {generatedSitemap && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: "auto" }}
                  exit={{ opacity: 0, height: 0 }}
                  className="space-y-2 overflow-hidden"
                >
                  <div className="relative">
                    <textarea
                      readOnly
                      value={generatedSitemap}
                      rows={6}
                      className="w-full dark:bg-[#111] bg-gray-100 border dark:border-[#333] border-gray-300 rounded-md p-3 text-xs dark:text-gray-300 text-gray-700 font-mono focus:outline-none resize-none"
                    />
                    <button
                      onClick={handleCopySitemap}
                      className="absolute top-2 right-2 px-2 py-1 bg-blue-500 hover:bg-blue-600 text-white text-[10px] rounded transition-colors shadow-sm font-medium"
                    >
                      Copy XML
                    </button>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>

        <div className="p-4 border-t dark:border-[#333] border-gray-200 flex justify-end gap-2 bg-gray-50 dark:bg-[#1A1A1A]">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-md text-sm font-medium dark:text-gray-300 text-gray-600 hover:bg-gray-200 dark:hover:bg-[#333] transition-colors"
          >
            {t("Cancel")}
          </button>
          <button
            onClick={handleSave}
            className="px-4 py-2 rounded-md text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 transition-colors flex items-center gap-2 shadow-sm"
          >
            <Save size={16} />
            {t("Save Settings")}
          </button>
        </div>
      </motion.div>
    </div>
  );
};
